export type ReportValidationIssue = {
  code: string;
  path: string;
  message: string;
};

export type ReportDomainErrorCode =
  | "REPORT_DISABLED"
  | "REPORT_ACTOR_FORBIDDEN"
  | "REPORT_INPUT_INVALID"
  | "REPORT_LEVEL_NOT_FOUND"
  | "REPORT_LEVEL_TYPE_INVALID"
  | "REPORT_ASSIGNMENT_NOT_FOUND"
  | "REPORT_ASSIGNMENT_CONFLICT"
  | "REPORT_ASSIGNMENT_NOT_DRAFT"
  | "REPORT_PUBLISHED_IMMUTABLE"
  | "REPORT_ARCHIVED_IMMUTABLE"
  | "REPORT_PUBLICATION_INVALID"
  | "REPORT_REPLACEMENT_REQUIRED"
  | "REPORT_REPLACEMENT_MISMATCH"
  | "REPORT_LOCALIZATION_NOT_FOUND"
  | "REPORT_FIELD_NOT_FOUND"
  | "REPORT_FIELD_LOCALIZATION_NOT_FOUND"
  | "REPORT_RUBRIC_NOT_FOUND"
  | "REPORT_RUBRIC_CONFLICT"
  | "REPORT_CRITERION_NOT_FOUND"
  | "REPORT_CRITERION_LOCALIZATION_NOT_FOUND"
  | "REPORT_SCALE_OPTION_NOT_FOUND"
  | "REPORT_SCALE_LOCALIZATION_NOT_FOUND"
  | "REPORT_REASON_NOT_FOUND"
  | "REPORT_REASON_LOCALIZATION_NOT_FOUND"
  | "REPORT_BINDING_NOT_FOUND"
  | "REPORT_BINDING_CONFLICT"
  | "REPORT_VERSION_MISMATCH"
  | "REPORT_NOT_EMPTY"
  | "REPORT_NO_CHANGES"
  | "REPORT_USER_NOT_FOUND"
  | "REPORT_NOT_ENROLLED"
  | "REPORT_NOT_CONFIGURED"
  | "REPORT_LOCALIZATION_UNAVAILABLE"
  | "REPORT_LEVEL_NOT_STARTED"
  | "REPORT_LEVEL_WRONG_TYPE"
  | "REPORT_DRAFT_INPUT_INVALID"
  | "REPORT_SUBMISSION_NOT_FOUND"
  | "REPORT_REVISION_CONFLICT"
  | "REPORT_REVISION_STALE"
  | "REPORT_IDEMPOTENCY_CONFLICT"
  | "REPORT_SUBMISSION_IMMUTABLE"
  | "REPORT_ALREADY_SUBMITTED"
  | "REPORT_NOT_REJECTED"
  | "REPORT_RESUBMISSION_REQUIRED"
  | "REPORT_CORRECTION_REQUIRED"
  | "REPORT_REVIEWER_FORBIDDEN"
  | "REPORT_SELF_REVIEW_FORBIDDEN"
  | "REPORT_NOT_PENDING_REVIEW"
  | "REPORT_CLAIM_CONFLICT"
  | "REPORT_CLAIM_NOT_OWNER"
  | "REPORT_CLAIM_EXPIRED"
  | "REPORT_REVIEW_INPUT_INVALID"
  | "REPORT_RUBRIC_MISMATCH"
  | "REPORT_REASON_MISMATCH"
  | "REPORT_REVIEW_NOT_FOUND"
  | "REPORT_APPROVAL_ENGINE_UNAVAILABLE"
  | "REPORT_ATTACHMENTS_DISABLED"
  | "REPORT_ATTACHMENT_STORAGE_UNAVAILABLE"
  | "REPORT_ATTACHMENT_SCANNER_UNAVAILABLE"
  | "REPORT_ATTACHMENT_NOT_FOUND"
  | "REPORT_ATTACHMENT_REVISION_IMMUTABLE"
  | "REPORT_ATTACHMENT_REVISION_STALE"
  | "REPORT_ATTACHMENT_NAME_INVALID"
  | "REPORT_ATTACHMENT_TYPE_INVALID"
  | "REPORT_ATTACHMENT_CHECKSUM_MISMATCH"
  | "REPORT_ATTACHMENT_EMPTY"
  | "REPORT_ATTACHMENT_TOO_LARGE"
  | "REPORT_ATTACHMENT_COUNT_EXCEEDED"
  | "REPORT_ATTACHMENT_AGGREGATE_EXCEEDED"
  | "REPORT_ATTACHMENT_UPLOAD_INCOMPLETE"
  | "REPORT_ATTACHMENT_SCAN_PENDING"
  | "REPORT_ATTACHMENT_SCAN_REJECTED"
  | "REPORT_ATTACHMENT_CLEANUP_RETRY"
  | "REPORT_STATE_CORRUPT"
  | "REPORT_INTERNAL_ERROR";

export class ReportDomainError extends Error {
  readonly code: ReportDomainErrorCode;
  readonly issues: ReportValidationIssue[];

  constructor(
    code: ReportDomainErrorCode,
    message: string,
    issues: ReportValidationIssue[] = [],
  ) {
    super(message);
    this.name = "ReportDomainError";
    this.code = code;
    this.issues = issues;
  }
}

export function isReportDomainError(
  error: unknown,
  code?: ReportDomainErrorCode,
): error is ReportDomainError {
  if (!(error instanceof ReportDomainError)) return false;
  return code === undefined || error.code === code;
}
