export const progressionLevels = [
  { number: 1, requiredXp: 0 },
  { number: 2, requiredXp: 10 },
  { number: 3, requiredXp: 25 },
  { number: 4, requiredXp: 75 },
  { number: 5, requiredXp: 100 },
  { number: 6, requiredXp: 250 },
  { number: 7, requiredXp: 500 },
  { number: 8, requiredXp: 750 },
  { number: 9, requiredXp: 1000 },
  { number: 10, requiredXp: 1300 },
  { number: 11, requiredXp: 1600 },
  { number: 12, requiredXp: 2000 },
  { number: 13, requiredXp: 2500 },
  { number: 14, requiredXp: 2750 },
  { number: 15, requiredXp: 3000 },
  { number: 16, requiredXp: 3500 },
] as const;

export const progressionTasks = [
  {
    code: "lvl_01_pocket_registration",
    stepNumber: 1,
    title: "Регистрация аккаунта Pocket",
    description: "Перейдите в Pocket через нашу ссылку и зарегистрируйтесь. Задание завершится только после Registration postback.",
    xpReward: 15,
    kind: "pocket_registration",
    completionMethod: "pocket_postback",
    actionLabel: "Перейти в Pocket",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_02_platform_intro_lesson",
    stepNumber: 2,
    title: "Пройти урок: знакомство с платформой",
    description: "Изучите вводный урок о платформе и завершите его.",
    xpReward: 30,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_03_demo_5_trades_report",
    stepNumber: 3,
    title: "Провести 5 сделок на демо и отправить отчёт",
    description: "Проведите пять учебных сделок на демо-счёте и отправьте отчёт ментору.",
    xpReward: 30,
    kind: "task_report",
    completionMethod: "report_approval",
    actionLabel: "Отправить отчёт",
    requiresReport: true,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_04_any_deposit",
    stepNumber: 4,
    title: "Сделать первый депозит",
    description: "Задание подтверждается автоматически после первого депозитного postback от Pocket.",
    xpReward: 10,
    kind: "deposit_checkpoint",
    completionMethod: "deposit_postback",
    actionLabel: "Проверить депозит",
    requiresReport: false,
    isCheckpoint: true,
    balanceThreshold: null,
  },
  {
    code: "lvl_05_technical_analysis_lesson",
    stepNumber: 5,
    title: "Пройти урок по техническому анализу",
    description: "Изучите основы технического анализа и завершите урок.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_06_news_trading_lesson",
    stepNumber: 6,
    title: "Пройти урок по торговле новостями",
    description: "Изучите правила торговли на новостях и завершите урок.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_07_ta_news_trades_report",
    stepNumber: 7,
    title: "30 сделок по теханализу и 5 сделок по новостям",
    description: "Проведите 30 сделок по техническому анализу и 5 сделок по новостям, затем отправьте отчёт.",
    xpReward: 10,
    kind: "task_report",
    completionMethod: "report_approval",
    actionLabel: "Отправить отчёт",
    requiresReport: true,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_08_balance_500",
    stepNumber: 8,
    title: "Проверка баланса 500 USD",
    description: "Проверьте через Pocket user-info, что реальный баланс достиг 500 USD.",
    xpReward: 10,
    kind: "balance_checkpoint",
    completionMethod: "balance_check",
    actionLabel: "Проверить баланс",
    requiresReport: false,
    isCheckpoint: true,
    balanceThreshold: 500,
  },
  {
    code: "lvl_09_stochastic_lesson",
    stepNumber: 9,
    title: "Пройти урок по стохастику",
    description: "Изучите торговую стратегию со стохастическим осциллятором.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_10_bollinger_lesson",
    stepNumber: 10,
    title: "Пройти урок по Боллинджеру",
    description: "Изучите торговую стратегию с полосами Боллинджера.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_11_stochastic_bollinger_trades_report",
    stepNumber: 11,
    title: "50 сделок по стохастику и 50 сделок по Боллинджеру",
    description: "Проведите по 50 сделок по каждой стратегии и отправьте отчёт ментору.",
    xpReward: 10,
    kind: "task_report",
    completionMethod: "report_approval",
    actionLabel: "Отправить отчёт",
    requiresReport: true,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_12_balance_1000",
    stepNumber: 12,
    title: "Проверка баланса 1000 USD",
    description: "Проверьте через Pocket user-info, что реальный баланс достиг 1000 USD.",
    xpReward: 10,
    kind: "balance_checkpoint",
    completionMethod: "balance_check",
    actionLabel: "Проверить баланс",
    requiresReport: false,
    isCheckpoint: true,
    balanceThreshold: 1000,
  },
  {
    code: "lvl_13_trading_journal_lesson",
    stepNumber: 13,
    title: "Пройти урок по ведению дневника трейдера",
    description: "Изучите правила ведения торгового дневника и завершите урок.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_14_risk_management_lesson",
    stepNumber: 14,
    title: "Пройти урок по риск-менеджменту",
    description: "Изучите правила управления риском и завершите урок.",
    xpReward: 10,
    kind: "lesson",
    completionMethod: "manual",
    actionLabel: "Завершить урок",
    requiresReport: false,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_15_mentor_session",
    stepNumber: 15,
    title: "Сессия с ментором",
    description: "Пройдите сессию с ментором и отправьте результат на подтверждение готовности.",
    xpReward: 10,
    kind: "mentor_approval",
    completionMethod: "report_approval",
    actionLabel: "Отправить на проверку",
    requiresReport: true,
    isCheckpoint: false,
    balanceThreshold: null,
  },
  {
    code: "lvl_16_balance_2000",
    stepNumber: 16,
    title: "Проверка баланса 2000 USD",
    description: "Проверьте через Pocket user-info, что реальный баланс достиг 2000 USD.",
    xpReward: 10,
    kind: "balance_checkpoint",
    completionMethod: "balance_check",
    actionLabel: "Проверить баланс",
    requiresReport: false,
    isCheckpoint: true,
    balanceThreshold: 2000,
  },
] as const;
