/**
 * AFD-5D3 — the authoritative finding-catalog inventory, taken FROM SOURCE.
 *
 * This is a reporting tool, not an assertion suite. It exists so the audit's
 * catalog document and machine-readable JSON are generated by reading the
 * running catalog rather than transcribed by hand — which is how two matrices
 * came to be wrong in AFD-5D2A.
 *
 * It emits JSON on stdout and writes nothing.
 */
import { ANALYSIS_CATALOG, CATALOG_CODES } from "../../src/lib/analysis/analysis-catalog";
import {
  ANALYSIS_CATALOG_VERSION,
  ANALYSIS_THRESHOLDS,
  FINDING_CODES,
  ANALYSIS_SECTIONS,
  FINDING_SEVERITIES,
} from "../../src/lib/analysis/analysis-contract";
import { SUPPORT_TIERS } from "../../src/lib/analysis/analysis-support";
import {
  SUFFICIENCY_REASON_CODES,
  UNEMITTED_REASON_CODES,
  ANALYSIS_STATUSES,
  SUFFICIENCY_STATUSES,
} from "../../src/lib/analysis/analysis-sufficiency";
import fs from "node:fs";
import path from "node:path";

const rulesSource = fs.readFileSync(
  path.join(process.cwd(), "src/lib/analysis/analysis-rules.ts"),
  "utf8",
);

/**
 * Which analytics mode(s) may emit each code, derived from the rule function
 * that contains it. Function boundaries are read from source rather than
 * guessed: `eventDate*` builders run only in event-date mode, `cohort*` only in
 * cohort mode, and `standingQuestions` runs in both.
 */
type Span = { name: string; start: number; end: number };

function ruleSpans(): Span[] {
  const pattern = /^(?:export )?function (\w+)\(/gm;
  const found: { name: string; start: number }[] = [];
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(rulesSource)) !== null) {
    found.push({ name: match[1]!, start: match.index });
  }
  return found.map((entry, index) => ({
    name: entry.name,
    start: entry.start,
    end: index + 1 < found.length ? found[index + 1]!.start : rulesSource.length,
  }));
}

const SPANS = ruleSpans();

function modesFor(code: string): string[] {
  const needle = `code: "${code}"`;
  const owners = SPANS.filter((span) => rulesSource.slice(span.start, span.end).includes(needle));
  const modes = new Set<string>();
  for (const owner of owners) {
    if (owner.name.startsWith("eventDate")) modes.add("event_date");
    else if (owner.name.startsWith("cohort")) modes.add("acquisition_cohort");
    else if (owner.name === "standingQuestions") {
      modes.add("event_date");
      modes.add("acquisition_cohort");
    } else modes.add(`via:${owner.name}`);
  }
  if (modes.size === 0) modes.add("unreferenced");
  return [...modes].sort();
}

function emittingFunctions(code: string): string[] {
  const needle = `code: "${code}"`;
  return SPANS.filter((span) => rulesSource.slice(span.start, span.end).includes(needle)).map(
    (span) => span.name,
  );
}

const DENOMINATOR_OPERAND: Readonly<Record<string, string>> = {
  funnel_rate_level: "denominator",
  cohort_rate_level: "denominator",
  small_sample_rate: "denominator",
  member_rate_differs_from_aggregate: "memberDenominator",
  member_clicks_without_registrations: "clicks",
  member_registrations_without_deposits: "pocketRegistrations",
  cohort_median_lag: "sampleSize",
};

const inventory = {
  generatedFrom: "src/lib/analysis (source of truth)",
  catalogVersion: ANALYSIS_CATALOG_VERSION,
  thresholds: ANALYSIS_THRESHOLDS,
  vocabularies: {
    sections: ANALYSIS_SECTIONS,
    severities: FINDING_SEVERITIES,
    supportTiers: SUPPORT_TIERS,
    analysisStatuses: ANALYSIS_STATUSES,
    sufficiencyStatuses: SUFFICIENCY_STATUSES,
    sufficiencyReasonCodes: SUFFICIENCY_REASON_CODES,
    unemittedReasonCodes: UNEMITTED_REASON_CODES,
  },
  counts: {
    findingCodesInContract: FINDING_CODES.length,
    catalogEntries: CATALOG_CODES.length,
    reasonCodes: SUFFICIENCY_REASON_CODES.length,
  },
  findings: CATALOG_CODES.map((code) => {
    const entry = ANALYSIS_CATALOG[code];
    return {
      code,
      section: entry.section,
      severity: entry.severity,
      requiredOperands: entry.requiredOperands,
      denominatorOperand: DENOMINATOR_OPERAND[code] ?? null,
      supportTierCapability:
        DENOMINATOR_OPERAND[code] === undefined
          ? "always descriptive"
          : "descriptive | moderate | strong by denominator",
      emittedInModes: modesFor(code),
      emittedByRules: rulesSource.includes(`code: "${code}"`),
      emittingFunctions: emittingFunctions(code),
    };
  }),
};

console.log(JSON.stringify(inventory, null, 2));
