/**
 * AFFILIATE-PLATFORM-V1 §17/§19/§43 — staff control of partner logins.
 *
 * GET   list the logins of one partner
 * POST  create a login
 * PATCH enable, disable, or force a password reset
 *
 * STAFF CREATE PARTNER ACCESS. THEY DO NOT HOLD IT. A CRM operator cannot sign
 * in as a partner through this route or any other: there is no impersonation
 * path, and the partner session is a different cookie signed with a different
 * secret in a different table. What staff can do is create a credential and
 * hand it over once.
 *
 * THE INITIAL PASSWORD IS GENERATED BY THE SERVER AND RETURNED ONCE. An
 * operator-chosen password would be one an operator knows, and a partner
 * console that a member of staff can enter is not a tenant boundary.
 *
 * DISABLING A LOGIN STOPS SESSIONS AND TOUCHES NOTHING ELSE. §43: no
 * attribution, no conversion, no qualification and no commission is altered,
 * hidden or reversed by disabling a person's access. The `sessionEpoch` bump is
 * what makes it immediate rather than eventual.
 */
import { NextResponse } from "next/server";
import crypto from "node:crypto";
import { z } from "zod";
import { createAuditLog } from "@/lib/audit";
import { prisma } from "@/lib/prisma";
import { AffiliateInputError, AffiliateNotFoundError } from "@/lib/crm/affiliates";
import {
  affiliateErrorResponse,
  affiliateHeaders,
  readBoundedJson,
  requireAffiliateCsrf,
  requireAffiliateManager,
  requireAffiliateReader,
  resolveAffiliateActorUserId,
} from "@/lib/crm/affiliate-routes";
import { crmRequestId } from "@/lib/crm/session";
import { randomBase32Id } from "@/lib/affiliate/random-id";
import {
  hashPartnerPassword,
  normalisePartnerEmail,
  PARTNER_PASSWORD_MIN_LENGTH,
} from "@/lib/affiliate/partner/credential";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const createSchema = z.object({
  affiliatePartnerId: z.number().int().positive(),
  email: z.string().trim().email().max(254),
  displayName: z.string().trim().min(1).max(160),
});

const patchSchema = z.object({
  partnerUserId: z.string().trim().length(32),
  action: z.enum(["disable", "enable", "reset_password"]),
});

/**
 * A generated initial password.
 *
 * 32 base64url characters of CSPRNG output. Comfortably above the policy floor,
 * and not something a human chose, so it cannot be a password reused from
 * somewhere else.
 */
function generateInitialPassword(): string {
  return crypto.randomBytes(24).toString("base64url");
}

export async function GET(request: Request) {
  const requestId = crmRequestId();
  const headers = affiliateHeaders(requestId);
  try {
    await requireAffiliateReader();
    const raw = new URL(request.url).searchParams.get("affiliatePartnerId");
    const partnerId = Number(raw);
    if (!Number.isInteger(partnerId) || partnerId <= 0) {
      throw new AffiliateInputError("crm.affiliates.partner_users.partner_required");
    }

    const rows = await prisma.affiliatePartnerUser.findMany({
      where: { affiliatePartnerId: partnerId },
      orderBy: { id: "asc" },
      // `passwordHash` is NOT selected. A digest is not a secret, but it is a
      // thing to crack offline, and no CRM surface has a reason to hold one.
      select: {
        publicId: true,
        email: true,
        displayName: true,
        status: true,
        sessionEpoch: true,
        lastLoginAt: true,
        passwordUpdatedAt: true,
        createdAt: true,
        disabledAt: true,
      },
    });

    return NextResponse.json(
      {
        items: rows.map((row) => ({
          partnerUserId: row.publicId,
          email: row.email,
          displayName: row.displayName,
          status: row.status,
          sessionEpoch: row.sessionEpoch,
          lastLoginAt: row.lastLoginAt?.toISOString() ?? null,
          passwordUpdatedAt: row.passwordUpdatedAt?.toISOString() ?? null,
          disabledAt: row.disabledAt?.toISOString() ?? null,
          createdAt: row.createdAt.toISOString(),
        })),
        total: rows.length,
      },
      { headers },
    );
  } catch (error) {
    return affiliateErrorResponse(error, requestId, headers);
  }
}

export async function POST(request: Request) {
  const requestId = crmRequestId();
  const headers = affiliateHeaders(requestId);
  try {
    await requireAffiliateManager();
    await requireAffiliateCsrf(request);
    const actorUserId = await resolveAffiliateActorUserId();

    const parsed = createSchema.safeParse(await readBoundedJson(request));
    if (!parsed.success) throw new AffiliateInputError("crm.affiliates.partner_users.invalid");

    const partner = await prisma.affiliatePartner.findUnique({
      where: { id: parsed.data.affiliatePartnerId },
      select: { id: true, code: true, status: true },
    });
    if (partner === null) throw new AffiliateNotFoundError("crm.affiliates.partner_not_found");
    if (partner.status === "archived") {
      throw new AffiliateInputError("crm.affiliates.partner_users.partner_archived");
    }

    const email = normalisePartnerEmail(parsed.data.email);
    const password = generateInitialPassword();

    let created;
    try {
      created = await prisma.affiliatePartnerUser.create({
        data: {
          publicId: randomBase32Id(),
          affiliatePartnerId: partner.id,
          email,
          passwordHash: await hashPartnerPassword(password),
          displayName: parsed.data.displayName,
          status: "active",
          createdByUserId: actorUserId,
        },
        select: { publicId: true, email: true, displayName: true, createdAt: true },
      });
    } catch (error) {
      // A GLOBALLY UNIQUE ADDRESS. The refusal names the constraint, not the
      // partner that already holds it: a CRM operator with this permission
      // could look it up, but the error message should not do it for them.
      if ((error as { code?: string }).code === "P2002") {
        throw new AffiliateInputError("crm.affiliates.partner_users.email_taken");
      }
      throw error;
    }

    await createAuditLog({
      userId: actorUserId,
      action: "AFFILIATE_PARTNER_USER_CREATED",
      entityType: "AFFILIATE_PARTNER_USER",
      entityId: created.publicId,
      // The address and the partner. NEVER the password, and never its hash.
      metadata: { affiliatePartnerId: partner.id, affiliatePartnerCode: partner.code, email },
      request,
    });

    return NextResponse.json(
      {
        partnerUserId: created.publicId,
        email: created.email,
        displayName: created.displayName,
        createdAt: created.createdAt.toISOString(),
        // THE ONE AND ONLY REVEAL. No read path returns this again, and the
        // partner is expected to change it on first sign-in.
        initialPassword: password,
        initialPasswordNotice: "shown_once",
        passwordPolicyMinLength: PARTNER_PASSWORD_MIN_LENGTH,
      },
      { status: 201, headers },
    );
  } catch (error) {
    return affiliateErrorResponse(error, requestId, headers);
  }
}

export async function PATCH(request: Request) {
  const requestId = crmRequestId();
  const headers = affiliateHeaders(requestId);
  try {
    await requireAffiliateManager();
    await requireAffiliateCsrf(request);
    const actorUserId = await resolveAffiliateActorUserId();

    const parsed = patchSchema.safeParse(await readBoundedJson(request));
    if (!parsed.success) throw new AffiliateInputError("crm.affiliates.partner_users.invalid");

    const existing = await prisma.affiliatePartnerUser.findUnique({
      where: { publicId: parsed.data.partnerUserId },
      select: { id: true, publicId: true, affiliatePartnerId: true, status: true },
    });
    if (existing === null) {
      throw new AffiliateNotFoundError("crm.affiliates.partner_users.not_found");
    }

    const now = new Date();
    let revealedPassword: string | null = null;

    if (parsed.data.action === "disable") {
      await prisma.affiliatePartnerUser.update({
        where: { id: existing.id },
        data: {
          status: "disabled",
          disabledAt: now,
          // IMMEDIATE, NOT EVENTUAL. Every token already issued stops
          // verifying on the next request rather than at its own expiry.
          sessionEpoch: { increment: 1 },
        },
      });
    } else if (parsed.data.action === "enable") {
      await prisma.affiliatePartnerUser.update({
        where: { id: existing.id },
        data: { status: "active", disabledAt: null },
      });
    } else {
      revealedPassword = generateInitialPassword();
      await prisma.affiliatePartnerUser.update({
        where: { id: existing.id },
        data: {
          passwordHash: await hashPartnerPassword(revealedPassword),
          passwordUpdatedAt: now,
          sessionEpoch: { increment: 1 },
        },
      });
    }

    await createAuditLog({
      userId: actorUserId,
      action: `AFFILIATE_PARTNER_USER_${parsed.data.action.toUpperCase()}`,
      entityType: "AFFILIATE_PARTNER_USER",
      entityId: existing.publicId,
      metadata: { affiliatePartnerId: existing.affiliatePartnerId },
      request,
    });

    return NextResponse.json(
      {
        partnerUserId: existing.publicId,
        action: parsed.data.action,
        ...(revealedPassword !== null
          ? { initialPassword: revealedPassword, initialPasswordNotice: "shown_once" }
          : {}),
      },
      { headers },
    );
  } catch (error) {
    return affiliateErrorResponse(error, requestId, headers);
  }
}
