import { NextResponse } from "next/server";
import { z } from "zod";
import { apiAuthErrorResponse, requireAdmin } from "@/lib/apiAuth";
import { createAuditLog } from "@/lib/audit";
import { csrfFailureResponse, validateCsrfToken } from "@/lib/csrf";
import { createNotification } from "@/lib/notifications";
import { prisma } from "@/lib/prisma";
import { validateJsonBody } from "@/lib/validation";
const schema = z.object({ userId: z.number().int().positive(), achievementId: z.number().int().positive(), action: z.enum(["grant", "revoke"]) });
export async function POST(request: Request) { if (!validateCsrfToken(request)) return csrfFailureResponse(request); let admin; try { admin = await requireAdmin(); } catch (error) { return apiAuthErrorResponse(error, request); } const parsed = await validateJsonBody(request, schema); if (!parsed.success) return parsed.response; const achievement = await prisma.achievement.findUnique({ where: { id: parsed.data.achievementId } }); if (!achievement) return NextResponse.json({ error: "NOT_FOUND" }, { status: 404 }); if (parsed.data.action === "grant") { await prisma.userAchievement.upsert({ where: { userId_achievementId: { userId: parsed.data.userId, achievementId: parsed.data.achievementId } }, update: { grantedById: admin.id, source: "admin" }, create: { userId: parsed.data.userId, achievementId: parsed.data.achievementId, grantedById: admin.id, source: "admin" } }); await createNotification({ userId: parsed.data.userId, type: "achievement_granted", title: "Получено достижение", message: achievement.title, metadata: { achievementId: achievement.id }, request }); } else { await prisma.userAchievement.deleteMany({ where: { userId: parsed.data.userId, achievementId: parsed.data.achievementId } }); await prisma.user.updateMany({ where: { id: parsed.data.userId, selectedAchievementId: parsed.data.achievementId }, data: { selectedAchievementId: null } }); } await createAuditLog({ userId: admin.id, action: parsed.data.action === "grant" ? "ADMIN_ACHIEVEMENT_GRANTED" : "ADMIN_ACHIEVEMENT_REVOKED", entityType: "Achievement", entityId: achievement.id, metadata: { targetUserId: parsed.data.userId }, request }); return NextResponse.json({ ok: true }); }
