/**
 * AFFILIATE-PLATFORM-V1 §30 — how a partner proves a delivery came from ATA.
 *
 * HMAC-SHA256 OVER A CANONICAL STRING, IN A HEADER, NEVER IN THE URL.
 *
 * WHY NOT IN THE QUERY. Because a URL ends up in the receiver's access log,
 * their proxy's log, their analytics and their browser history if a human ever
 * pastes it. Pocket's INBOUND contract puts its secret in `?ow=` and this
 * repository spends an nginx `log_format` and a `crit`-level error log keeping
 * it off disk — outbound is new, so it does not have to inherit that problem.
 *
 * WHAT IS SIGNED, AND WHY IT IS NOT JUST THE URL. The canonical string binds
 * four things together:
 *
 *     <secretVersion>\n<timestamp>\n<deliveryPublicId>\n<requestUrl>
 *
 *   * secretVersion — so a rotation is unambiguous. A receiver holding both the
 *     old and the new secret knows which to verify with instead of guessing.
 *   * timestamp — so a captured delivery cannot be replayed against the
 *     receiver indefinitely. It is the RECEIVER's freshness control, and the
 *     header states it explicitly rather than expecting them to parse a date
 *     out of the query.
 *   * deliveryPublicId — so one conversion delivered to two endpoint versions
 *     produces two distinct signatures, and a receiver can deduplicate on an
 *     identifier ATA guarantees is stable per logical delivery.
 *   * requestUrl — the payload itself, in full.
 *
 * THE SECRET IS NEVER ANY OTHER SECRET. §30 forbids reusing POSTBACK_SECRET,
 * SESSION_SECRET or ATTRIBUTION_TOKEN_SECRET here, and this signer cannot: the
 * key is a per-endpoint column generated by the server, and it has no code path
 * to any environment variable.
 */
import crypto from "node:crypto";

export const POSTBACK_SIGNATURE_HEADER = "x-ata-signature";
export const POSTBACK_TIMESTAMP_HEADER = "x-ata-timestamp";
export const POSTBACK_DELIVERY_HEADER = "x-ata-delivery-id";
export const POSTBACK_SECRET_VERSION_HEADER = "x-ata-secret-version";

/** 256 CSPRNG bits, base64url, 43 characters — the shape the CHECK enforces. */
export function generatePostbackSigningSecret(): string {
  return crypto.randomBytes(32).toString("base64url");
}

export function canonicalSignaturePayload(input: {
  secretVersion: number;
  timestamp: string;
  deliveryPublicId: string;
  requestUrl: string;
}): string {
  return [input.secretVersion, input.timestamp, input.deliveryPublicId, input.requestUrl].join("\n");
}

export function signPostback(
  secret: string,
  input: { secretVersion: number; timestamp: string; deliveryPublicId: string; requestUrl: string },
): string {
  return crypto
    .createHmac("sha256", secret)
    .update(canonicalSignaturePayload(input))
    .digest("hex");
}

/**
 * The headers one attempt carries.
 *
 * NOTHING ELSE IS SENT. No cookie, no authorization header, no ATA session, no
 * internal request id and no learner-derived value. A partner's server learns
 * exactly what the URL says plus these four headers.
 */
export function postbackHeaders(input: {
  secret: string;
  secretVersion: number;
  deliveryPublicId: string;
  requestUrl: string;
  now: Date;
}): Record<string, string> {
  const timestamp = input.now.toISOString();
  return {
    [POSTBACK_TIMESTAMP_HEADER]: timestamp,
    [POSTBACK_DELIVERY_HEADER]: input.deliveryPublicId,
    [POSTBACK_SECRET_VERSION_HEADER]: String(input.secretVersion),
    [POSTBACK_SIGNATURE_HEADER]: signPostback(input.secret, {
      secretVersion: input.secretVersion,
      timestamp,
      deliveryPublicId: input.deliveryPublicId,
      requestUrl: input.requestUrl,
    }),
    "User-Agent": "ATA-Postback/1",
    Accept: "*/*",
  };
}
